### ISSUE TITLE
ALPS make has error

### ISSUE THREAD

**Issue by Cjq275** [snalli/mnemosyne-gcc#17]
Hello,
When we build ALPS. There are some error:

In file included from /home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/test/unit/layers/test_extentheap.cc:23:0:
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/extentheap.hh: In instantiation of ‘void alps::Extent<Context, TPtr, PPtr>::mark_alloc(Context&) [with Context = Context; TPtr = alps::TPtr; PPtr = alps::PPtr]’:
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/extentheap.hh:180:13:   required from ‘alps::ErrorCode alps::ExtentHeap<Context, TPtr, PPtr>::alloc_extent(Context&, size_t, alps::Extent<Context, TPtr, PPtr>*) [with Context = Context; TPtr = alps::TPtr; PPtr = alps::PPtr; size_t = long unsigned int]’
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/test/unit/layers/test_extentheap.cc:57:5:   required from here
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/extentheap.hh:93:9: error: ‘class Context’ has no member named ‘do_nv’
         if (ctx.do_nv) {
         ^
In file included from /home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/extentheap.hh:29:0,
                 from /home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/test/unit/layers/test_extentheap.cc:23:
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/bits/freespacemap.hh: In instantiation of ‘void alps::FreeSpaceMap<Context, TPtr>::free_extent(Context&, const alps::ExtentInterval&) [with Context = Context; TPtr = alps::TPtr]’:
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/extentheap.hh:189:9:   required from ‘alps::ErrorCode alps::ExtentHeap<Context, TPtr, PPtr>::free_extent(Context&, alps::Extent<Context, TPtr, PPtr>&) [with Context = Context; TPtr = alps::TPtr; PPtr = alps::PPtr]’
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/test/unit/layers/test_extentheap.cc:71:9:   required from here
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/bits/freespacemap.hh:59:9: error: ‘class Context’ has no member named ‘do_v’
         if (ctx.do_v) {
         ^
In file included from /home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/test/unit/layers/test_extentheap.cc:23:0:
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/extentheap.hh: In instantiation of ‘void alps::Extent<Context, TPtr, PPtr>::mark_free(Context&) [with Context = Context; TPtr = alps::TPtr; PPtr = alps::PPtr]’:
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/extentheap.hh:190:9:   required from ‘alps::ErrorCode alps::ExtentHeap<Context, TPtr, PPtr>::free_extent(Context&, alps::Extent<Context, TPtr, PPtr>&) [with Context = Context; TPtr = alps::TPtr; PPtr = alps::PPtr]’
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/test/unit/layers/test_extentheap.cc:71:9:   required from here
/home/mnemomo/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/include/alps/layers/extentheap.hh:100:9: error: ‘class Context’ has no member named ‘do_nv’
         if (ctx.do_nv) {
         ^

make[2]: *** [test/unit/layers/CMakeFiles/test_extentheap.dir/test_extentheap.cc.o] Error 1
make[1]: *** [test/unit/layers/CMakeFiles/test_extentheap.dir/all] Error 2
make: *** [all] Error 2

There is no error in months ago.
Is there some update that have some error?

**Comment by pramalhe** [comment]
I see the same issue from a couple of days ago

**Comment by hvolos** [comment]
ALPS was originally developed separately from Mnemosyne as part of another project. We then ported ALPS to serve as a new memory allocator for Mnemosyne, but we haven't ported all the tests yet. 

For now, the latest commit 855f4526b64c2e35861f145ff7d5a5a303f5f4a3 disables the tests so that you can build ALPS. A new ticket #18 is opened to port the tests.
