### ISSUE TITLE
A bug in memory allocation

### ISSUE THREAD

**Issue by nachshonc** [snalli/mnemosyne-gcc#2]
On usermode/library/pmalloc/include/alps/include/alps/layers/bits/slab.hh Line 52, 
the computation of the size of the fixed part of the header is incorrect. It computes the sum of individual fields while ignoring padding. 
Either use #pragma pack or (preferably) replace the computation with 
(size_t)(void*)(&((nvSlabHeader*)0)->block_map), 
based on the offsetof kernel macro, to let the compiler computes the actual size.

**Comment by snalli** [comment]
can you please send me a pull request ?
