### ISSUE TITLE
failed compiling memcached

### ISSUE THREAD

**Issue by sjtugjy** [snalli/mnemosyne-gcc#4]
Here is the information about compiling errors:

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
(COMPILE)  build/bench/memcached/memcached-1.2.4-mtm/assoc.c
In file included from /usr/include/stdio.h:936:0,
                 from build/bench/memcached/memcached-1.2.4-mtm/assoc.c:16:
build/bench/memcached/memcached-1.2.4-mtm/assoc.c: In function 'assoc_init':
/usr/include/x86_64-linux-gnu/bits/stdio2.h:95:1: error: inlining failed in call to always_inline 'fprintf': 
 fprintf (FILE *__restrict __stream, const char *__restrict __fmt, ...)
 ^~~~~~~
build/bench/memcached/memcached-1.2.4-mtm/assoc.c:480:5: note: called from here
     fprintf(stderr, "assoc_init: hash_size = %d\n", hash_size);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scons: *** [build/bench/memcached/memcached-1.2.4-mtm/assoc.o] Error 1

**Comment by snalli** [comment]
remove fprintf or switch to gcc 6.2.1

**Comment by sjtugjy** [comment]
Hi, Snali

Thank you for your response. 
However, I use gcc-6.3.0.
Besides, I tried to remove fprintf. But it still reported the same problem with "snprintf" in other files.

**Comment by sjtugjy** [comment]
I have solved this problem.
I compile and install gcc-6.2.1 from source code and it works.

**Comment by snalli** [comment]
This can help you. 
https://github.com/snalli/mnemosyne-gcc/blob/alps/usermode/library/mtm/include/tm_def.h

**Comment by snalli** [comment]
Send me a patch if you modify this file for gcc 6.3

**Comment by snalli** [comment]
I believe the issue is with glibc and not with gcc.

**Comment by sjtugjy** [comment]
Thank you very much.
Yes, the issue is not with gcc. 
when glibc version is 2.23 and gcc version is 6.3.0, everything goes well.

**Comment by snalli** [comment]
Sorry about that. I'll make a note of it in the README.

**Comment by ivanium** [comment]
Hi, sorry to disturb you. I also have the same problem. Here are the information of compiling errors:

>`>>> scons --build-bench=memcached --config-ftrace`
> 
> scons: Reading SConscript files ...
> scons: done reading SConscript files.
> scons: Building targets ...
> (COMPILE)  build/bench/memcached/memcached-1.2.4-mtm/assoc.c
> In file included from /usr/include/stdio.h:936:0,
>                  from /usr/include/event2/event.h:195,
>                  from /usr/include/event.h:71,
>                  from bench/memcached/memcached-1.2.4-mtm/memcached.h:12,
>                  from build/bench/memcached/memcached-1.2.4-mtm/assoc.c:22:
> build/bench/memcached/memcached-1.2.4-mtm/assoc.c: In function 'assoc_init':
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:95:1: error: inlining failed in call to always_inline 'fprintf': 
>  fprintf (FILE *__restrict __stream, const char *__restrict __fmt, ...)
>  ^~~~~~~
> build/bench/memcached/memcached-1.2.4-mtm/assoc.c:479:5: note: called from here
>      fprintf(stderr, "assoc_init: hash_size = %d\n", hash_size);
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ...

I have glibc-2.23 and gcc-6.3.0 and I think the issue is with glibc. I can compile the memcached after I hacked the `tm_def.h` like this: (line 27)
`#if (__GLIBC__ == 2 && __GLIBC_MINOR__ > 19)` ->
`#if (__GLIBC__ == 2 && __GLIBC_MINOR__ > 23)`

I don't know what's wrong with my glibc. Could you please help me?

**Comment by snalli** [comment]
hmm..that is strange. the glibc minor version, which is 23, on your machine is greater than 19. so it shd work. well, i'll take a look when i find some time.
