### ISSUE TITLE
pfree assertion failed

### ISSUE THREAD

**Issue by sjtugjy** [snalli/mnemosyne-gcc#5]
I tried to modify the example code and ran into some errors.
The following code is okay.

```
void* reader()
{
        printf("(READER) persistent ptr =%p, sz=%d\n", ptr, sz);
        int i = 0;
        long rd;
        long *ptr1;
        while(i++ < count)
        {
                PTx { ptr1 = pmalloc(sz); rd = *ptr1; pfree(ptr1);  }
        }
}

void* writer()
{
        printf("(WRITER) persistent ptr =%p, sz=%d\n", ptr, sz);
        int i = 0;
        long wrt = 1;
        long *ptr2;
        while(i++ < count)
        {
                PTx { ptr2 = pmalloc(sz); *ptr2 = wrt; }
                //PTx { pfree(ptr2); }
        }
}
```

But after I split the transaction in reader like this
```
void* reader()
{
        printf("(READER) persistent ptr =%p, sz=%d\n", ptr, sz);
        int i = 0;
        long rd;
        long *ptr1;
        while(i++ < count)
        {
                PTx { ptr1 = pmalloc(sz); rd = *ptr1;  } 
                PTx { pfree(ptr1); }
        }
}
```

I get the error message once in every five runs:
simple: library/pmalloc/include/alps/include/alps/layers/bits/slab.hh:323: void alps::Slab<Context, TPtr, PPtr>::free_block(Context&, TPtr<void>) [with Context = Context; TPtr = alps::TPtr; PPtr = alps::TPtr]: Assertion `nvslab_->is_free(ctx, bid) == false' failed.
Aborted (core dumped)

I wonder how to fix this code. Thanks.

**Comment by snalli** [comment]
Use a debugger such as gdb to step through the code or collect a backtrace. That will help you figure out the solution.

**Comment by snalli** [comment]
Please use the github issues page to file confirmed bugs, preferably with a solution as a patch. For other doubts, just send me an email.
