### ISSUE TITLE
Is it possible to register/deregister threads?

### ISSUE THREAD

**Issue by pramalhe** [snalli/mnemosyne-gcc#7]
From what I understood, there are LOG_NUM (32) log chunks which becomes a hard-coded limitation to the number of threads that can be participate in transactions. Is there a way to increase this?

Increasing LOG_NUM in library/mcore/src/log/mgr.c works (up to 64 ?), but in our benchmarks we create/destroy lots of threads, which means we quickly exhaust this number. Is there an API in Mnemosyne to register and deregister a thread? 

Thanks,
Pedro

**Comment by hvolos** [comment]
One way would be to try to add calls to _ITM_initializeThread and _ITM_finalizeThread at places where you create and destroy threads.

**Comment by pramalhe** [comment]
Humm when I try to call these methods the linker can't find them. 
Don't worry, we'll work around it if needed. Thanks for the tip
