### ISSUE TITLE
Allocating large arrays (about 1k) causes some kind of corruption

### ISSUE THREAD

**Issue by pramalhe** [snalli/mnemosyne-gcc#9]
I've added an example called "bigalloc" to the pull request so you can try to repro on your side.
Can be compiled and run with:
 scons --build-example=bigalloc
./build/examples/bigalloc/bigalloc

Basically,  doing a pmalloc() of something like this causes some kind of memory corruption:
typedef struct {
    long long a[1000];
} myarray_t;

I might be missing something basic on the PTx or the struct definition... maybe the struct needs a TM_SOMETHING attribute? 
It works (most of the time) if the array has 500 entries.

**Comment by hvolos** [comment]
I pushed two fixes that I believe fix the problem you're seeing.

**Comment by pramalhe** [comment]
bigalloc now works and we can allocate bigger arrays.
Thank you so much Haris.  This unblocks our progress  :)

**Comment by hvolos** [comment]
Latest commit bb59f5c992a938e0cb26ef7e342316a26034035e fixes this issue
